---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: navno-cms-archive
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 3399
  ingresses:
     - https://cms-arkiv.intern.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  env:
    - name: APP_PORT
      value: "3399"
    - name: APP_BASEPATH
      value: "/"
    - name: APP_ORIGIN
      value: "https://cms-arkiv.intern.nav.no"
  openSearch:
    access: read
    instance: enonic-cms-archive
  accessPolicy:
    outbound:
      external:
        - host: cms-arkiv.intern.nav.no
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      memory: 2048Mi
