FROM node:22-bookworm-slim

RUN apt-get update \
    && apt-get --assume-yes --no-install-recommends install chromium \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app/xp-archive/server

ENV NODE_ENV=production
ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
ENV PUPPETEER_CACHE_DIR=/app/.puppeteer-cache
ENV PUPPETEER_TMP_DIR=/tmp/.puppeteer
ENV XDG_CONFIG_HOME=/tmp/.chromium
ENV XDG_CACHE_HOME=/tmp/.chromium

RUN mkdir -p /app/xp-archive/server /app/.puppeteer-cache /tmp/.puppeteer /tmp/.chromium \
    && chown -R node:node /app /tmp/.puppeteer /tmp/.chromium

COPY --chown=node:node --chmod=555 node_modules /app/node_modules/
COPY --chown=node:node --chmod=444 xp-archive/.env /app/xp-archive/
COPY --chown=node:node --chmod=555 xp-archive/node_modules* /app/xp-archive/node_modules/
COPY --chown=node:node --chmod=555 xp-archive/server/dist /app/xp-archive/server/dist/
COPY --chown=node:node --chmod=444 xp-archive/server/package.json /app/xp-archive/server/

USER node

EXPOSE 3499
CMD ["npm", "run", "start"]
