FROM node:22-alpine

WORKDIR /app/xp-archive/server

ENV NODE_ENV=production
ENV PUPPETEER_CACHE_DIR=/app/.puppeteer-cache
ENV PUPPETEER_TMP_DIR=/tmp/.puppeteer

COPY node_modules /app/node_modules/
COPY .cache/puppeteer /app/.puppeteer-cache/
COPY xp-archive/.env /app/xp-archive/
COPY xp-archive/node_modules /app/xp-archive/node_modules/
COPY xp-archive/server/dist /app/xp-archive/server/dist/
COPY xp-archive/server/package.json /app/xp-archive/server/

EXPOSE 3499
CMD ["npm", "run", "start"]
