FROM node:24-bookworm-slim

RUN apt-get update \
    && apt-get --assume-yes --no-install-recommends install chromium curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app/legacy-archive/server

ENV NODE_ENV=production
ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
ENV XDG_CONFIG_HOME=/tmp/.chromium
ENV XDG_CACHE_HOME=/tmp/.chromium

RUN mkdir -p /app/legacy-archive/server /tmp/.chromium \
    && chown -R node:node /app /tmp/.chromium

COPY --chown=root:root --chmod=755 node_modules /app/node_modules/
COPY --chown=root:root --chmod=755 legacy-archive/server/dist /app/legacy-archive/server/dist/
COPY --chown=root:root --chmod=755 legacy-archive/server/package.json /app/legacy-archive/server/

USER node

EXPOSE 3399
CMD ["npm", "run", "start"]
