FROM europe-north1-docker.pkg.dev/cgr-nav/pull-through/nav.no/node:24-dev

USER root
RUN apk add --no-cache chromium

WORKDIR /app/legacy-archive/server

ENV NODE_ENV=production
ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
ENV XDG_CONFIG_HOME=/tmp/.chromium
ENV XDG_CACHE_HOME=/tmp/.chromium

COPY --chown=root:root --chmod=755 nonsymlink/legacy-server/ /app/legacy-archive/server/

RUN mkdir -p /tmp/.chromium && chown 65532:65532 /tmp/.chromium

USER nonroot

EXPOSE 3399
CMD ["-r", "dotenv/config", "./dist/server/server.cjs", "dotenv_config_path=../.env"]
