FROM europe-north1-docker.pkg.dev/cgr-nav/pull-through/nav.no/node:24-slim

WORKDIR /app/legacy-archive/server

ENV NODE_ENV=production
ENV PUPPETEER_CACHE_DIR=/app/legacy-archive/server/puppeteer-cache
ENV XDG_CONFIG_HOME=/tmp/.chromium
ENV XDG_CACHE_HOME=/tmp/.chromium

COPY --chown=root:root --chmod=755 nonsymlink/legacy-server/ /app/legacy-archive/server/

USER nonroot

EXPOSE 3399
CMD ["-r", "dotenv/config", "./dist/server/server.cjs", "dotenv_config_path=../.env"]
