---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: navno-cms-archive
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 3399
  ingresses:
     - https://cms-arkiv.intern.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  openSearch:
    access: read
    instance: enonic-cms-archive
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 1024Mi
