---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: navno-xp-archive
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 3499
  ingresses:
     - {{ appOrigin }}/xp
  liveness:
    path: /xp/internal/isAlive
    initialDelay: 10
  readiness:
    path: /xp/internal/isReady
    initialDelay: 10
  accessPolicy:
    outbound:
      rules:
        - application: {{ xpFrontendApp }}
      external:
        - host: {{ xpHost }}
  envFrom:
    - secret: {{ secret }}
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 2048Mi
