---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: navno-xp-archive
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 3499
  ingresses:
     - {{ APP_ORIGIN }}/xp
  liveness:
    path: /xp/internal/isAlive
    initialDelay: 10
  readiness:
    path: /xp/internal/isReady
    initialDelay: 10
  env:
    - name: APP_PORT
      value: "3499"
    - name: APP_BASEPATH
      value: "/xp"
    - name: APP_ORIGIN
      value: {{ APP_ORIGIN }}
    - name: XP_ORIGIN
      value: https://{{ XP_HOST }}
  accessPolicy:
    outbound:
      external:
        - host: {{ XP_HOST }}
  envFrom:
    - secret: {{ secret }}
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 2048Mi
