---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: navno-xp-archive
  namespace: navno
  labels:
    team: navno
spec:
  image: {{ image }}
  port: 3499
  ingresses:
     - {{ appOrigin }}/xp
  liveness:
    path: /xp/internal/isAlive
    initialDelay: 10
  readiness:
    path: /xp/internal/isReady
    initialDelay: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  accessPolicy:
    outbound:
      rules:
        - application: {{ xpFrontendApp }}
      external:
        - host: {{ xpHost }}
        - host: cdn.nav.no
  envFrom:
    - secret: {{ secret }}
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      memory: 2048Mi
