name: Build and deploy XP archive (internal action)
inputs:
    naisEnv:
        required: true
        type: string
    VITE_APP_ORIGIN:
        required: true
    XP_ORIGIN:
        required: true
    HTML_RENDER_API:
        required: true

runs:
    using: composite
    steps:
        - name: Checkout repo
          runs-on: ubuntu-latest
          environment: ${{ inputs.naisEnv }}-xp
          permissions:
            contents: read
            id-token: write
          uses: actions/checkout@v4
        - name: Setup node.js
          uses: actions/setup-node@v4
          with:
              node-version: 22
              registry-url: https://npm.pkg.github.com
              cache: npm
              cache-dependency-path: '**/package-lock.json'
        - name: Install dependencies
          run: npm ci --include-workspace-root --workspace=common --workspace=xp-archive
          env:
              NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

        - name: Write .env for build
          shell: bash
          working-directory: xp-archive
          env:
              VITE_APP_ORIGIN: ${{ inputs.VITE_APP_ORIGIN }}
              XP_ORIGIN: ${{ inputs.XP_ORIGIN }}
              HTML_RENDER_API: ${{ inputs.HTML_RENDER_API }}
          run: |
              cat > .env <<EOF
              NODE_ENV=production
              APP_PORT=3499
              APP_BASEPATH=/xp
              VITE_APP_ORIGIN=$VITE_APP_ORIGIN
              XP_ORIGIN=$XP_ORIGIN
              HTML_RENDER_API=$HTML_RENDER_API
              EOF

        - name: Build application
          working-directory: xp-archive
          run: npm run build

        - name: Build and push docker image
          id: docker-push
          uses: nais/docker-build-push@v0
          with:
              team: navno
              project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
              identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
              dockerfile: Dockerfile_xp
              cache_from: '' # Disable cache
              cache_to: '' # Disable cache
              image_suffix: ${{ inputs.naisEnv }}

        - name: Deploy application
          uses: nais/deploy/actions/deploy@v2
          env:
              CLUSTER: ${{ inputs.naisEnv }}-gcp
              RESOURCE: xp-archive/.nais/config.yml
              VAR: image=${{ steps.docker-push.outputs.image }}
              VARS: xp-archive/.nais/vars/${{ inputs.naisEnv }}.yml
