name: internal-xp-archive-build-and-deploy
description: Builds the XP app, pushes a Docker image with NAIS, and deploys it
inputs:
    naisEnv:
        required: true
        description: NAIS environment (dev-gcp or prod-gcp)
    VITE_APP_ORIGIN:
        required: true
        description: Vite app origin URL
    XP_ORIGIN:
        required: true
        description: XP origin URL
    HTML_RENDER_API:
        required: true
        description: HTML render API endpoint

runs:
    using: composite
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: 24
              registry-url: https://npm.pkg.github.com
              cache: npm
              cache-dependency-path: '**/package-lock.json'

        - name: Install dependencies
          shell: bash
          run: npm ci --ignore-scripts --include-workspace-root --workspace=common --workspace=xp-archive
          env:
              NODE_AUTH_TOKEN: ${{ env.READER_TOKEN }}

        - name: Write .env for build
          shell: bash
          working-directory: xp-archive
          env:
              VITE_APP_ORIGIN: ${{ inputs.VITE_APP_ORIGIN }}
              XP_ORIGIN: ${{ inputs.XP_ORIGIN }}
              HTML_RENDER_API: ${{ inputs.HTML_RENDER_API }}
          run: |
              cat > .env <<EOF
              NODE_ENV=production
              APP_PORT=3499
              APP_BASEPATH=/xp
              VITE_APP_ORIGIN=$VITE_APP_ORIGIN
              XP_ORIGIN=$XP_ORIGIN
              HTML_RENDER_API=$HTML_RENDER_API
              EOF

        - name: Build application
          shell: bash
          working-directory: xp-archive
          run: npm run build

        - name: Build and push docker image
          id: docker-push
          uses: nais/docker-build-push@v0
          with:
              team: navno
              project_id: ${{ env.NAIS_MANAGEMENT_PROJECT_ID }}
              identity_provider: ${{ env.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
              dockerfile: Dockerfile_xp
              cache_from: '' # Disable cache
              cache_to: '' # Disable cache
              image_suffix: ${{ inputs.naisEnv }}

        - name: Deploy application
          uses: nais/deploy/actions/deploy@v2
          env:
              CLUSTER: ${{ inputs.naisEnv }}-gcp
              RESOURCE: xp-archive/.nais/config.yml
              VAR: image=${{ steps.docker-push.outputs.image }}
              VARS: xp-archive/.nais/vars/${{ inputs.naisEnv }}.yml
