name: Build and deploy XP archive to prod
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - package*.json
      - xp-archive/**/*
      - common/**/*

jobs:
  build-and-deploy:
    name: Build and deploy to prod
    environment: prod-xp
    permissions:
      contents: "read"
      id-token: "write"
    uses: ./.github/workflows/.xp-archive-deploy.yml
    with:
      naisEnv: prod
      VITE_APP_ORIGIN: https://cms-arkiv.ansatt.nav.no
      XP_ORIGIN: https://www.nav.no
      HTML_RENDER_API: http://nav-enonicxp-frontend/render-from-props
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
