name: Build and deploy XP archive (dev)
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - package*.json
      - xp-archive/**/*
      - common/**/*

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm ci --include-workspace-root --workspace=common --workspace=xp-archive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Set env vars
        working-directory: xp-archive
        run: |
          cat > .env <<EOF
          NODE_ENV=production
          VITE_APP_ORIGIN=https://cms-arkiv.ansatt.dev.nav.no
          APP_PORT=3499
          APP_BASEPATH=/xp
          XP_ORIGIN=https://www.dev.nav.no
          HTML_RENDER_API=http://nav-enonicxp-frontend-dev1/render-from-props
          EOF
      - name: Build application
        run: npm run build
        working-directory: xp-archive
      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: personbruker
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          dockerfile: Dockerfile_xp-archive
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: xp-archive/.nais/config.yml
          VAR: image=${{ steps.docker-push.outputs.image }}
          VARS: xp-archive/.nais/vars/dev.yml
