name: Build and deploy XP archive to dev
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - package*.json
            - xp-archive/**/*
            - common/**/*

jobs:
    build-and-deploy:
        name: Build and deploy to dev
        permissions:
            contents: read
            id-token: write
        uses: internal_build-and-deploy-xp.yml
        with:
            naisEnv: dev
            VITE_APP_ORIGIN: https://cms-arkiv.ansatt.dev.nav.no
            XP_ORIGIN: https://www.dev.nav.no
            HTML_RENDER_API: http://nav-enonicxp-frontend-dev1/render-from-props
        secrets:
            READER_TOKEN: ${{ secrets.READER_TOKEN }}
            NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
